### ISSUE TITLE
Error: python setup.py egg_info did not run successfully (Ubuntu)

### ISSUE THREAD

**Issue by Maru-Yasa** [shhossain/FaceDB#10]
Got this error when trying to install from pip with venv, but works fine if I run locally

```
Collecting facedb
  Using cached FaceDB-0.0.11.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jxm2tbc8/facedb_264dbc4cde644c5fa4b895d2e1cc1f9c/setup.py", line 13, in <module>
          with open("requirements.txt") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

OS: Ubuntu 22.04.3 LTS x86_64
Python Version: 3.10.12

**Comment by Maru-Yasa** [comment]
Maybe adding this to setup.py could solve this issue?

![image](https://github.com/shhossain/FaceDB/assets/41475719/5db3150e-a1fa-49d0-aff3-040bba270764)

**Comment by shhossain** [comment]
@Maru-Yasa, I'll review the issue and get back to you shortly.

**Comment by shhossain** [comment]
@Maru-Yasa, meanwhile, you can use this: 
```bash
pip install git+https://github.com/shhossain/FaceDB.git
```

**Comment by Maru-Yasa** [comment]
thanks that's work fine,

**Comment by shhossain** [comment]
@Maru-Yasa, the issue was with MANIFEST.in. It seems there have been updates with pip or something similar, as it worked previously without the MANIFEST file. I've added the file now, so it should work fine.

**Comment by Maru-Yasa** [comment]
@shhossain thank you, I've tried and that's works as I expected
